---
# tasks file for ansible-role-patch
- name: Updating RHEL based systems
  ansible.builtin.yum:
    name: '*'
    state: latest
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
 
- name: Updating Debian based systems
  ansible.builtin.apt:
    name: '*'
    state: latest
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Updating Windows based systems
  ansible.windows.win_updates:
    state: installed
  when: ansible_os_family == 'Windows'
